import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  const link = encodeURIComponent("//[]()?");
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>index page</h1>
        <ul>
          <li>Link: {link}</li>
          <li><a href={`/${link}`}>Link to url</a> {`/${link}`}</li>
          <li><a href={`/?uid=${link}`}>Link to redirect</a> {`/?uid=${link}`}</li>
        </ul>



      </main>
    </div>
  )
}
